### ISSUE TITLE
some problems 

### ISSUE THREAD

**Issue by Sarfroz** [chihebnabil/vuejs-invoice-template#1]
hi can i ask some questions regarding this invoice system? I have my own but little different from yours. I am new to this system

**Comment by chihebnabil** [comment]
Hello @Sarfroz  , 

Thank you for reaching me !

How can i help you ?

**Comment by Sarfroz** [comment]
if you donot mind can we connect on skype. i will not make you bored just
little queries.

**Comment by Sarfroz** [comment]
[image: Screen Shot 2019-07-06 at 11.18.40 PM.png]
i am creating invoice system for my friend so i am new to this . You see
when i update one value other input value is also updated

**Comment by chihebnabil** [comment]
@Sarfroz (screenshot don't show up) can you please send your issue via email will try to check it for you

**Comment by Sarfroz** [comment]
can you share your mail??

**Comment by Sarfroz** [comment]
my email is khanaman53@gmail.com
